services:
  php:
    image: php:8.0-apache
    container_name: php_container
    ports:
      - "8000:80"
    volumes:
      - C:\xampp\htdocs\leaf:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: blog_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
